Add the pop-up additional BoxShadow property.
AvaloniaUtils/DialogHost.Avalonia pull request #40
Opened 2024-01-07 05:34 UTC by wj8400684

<img width="840" alt="截屏2024-01-07 13 34 44" src="https://github.com/AvaloniaUtils/DialogHost.Avalonia/assets/39239954/dc1d50a6-96c1-43f2-9c8b-e8f1ccc3ea31">

2024-01-07 13:02 UTC, SKProCH requested changes
Everything else looks good

2024-01-07 13:02 UTC, SKProCH commented on DialogHost.Avalonia/DialogHost.axaml
Can you revert the formatting changes in this file, please?

2024-01-07 13:40 UTC, wj8400684 commented on DialogHost.Avalonia/DialogHost.axaml
That's about it. Please change it.

2024-01-07 13:40 UTC, closed without merging

2024-01-09 07:52 UTC, SKProCH commented
Hello, @wj8400684 

Why you closed the PR?